/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RetirementLivingRouteImport } from './routes/retirement-living'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SwitchstarRouteImport } from './routes/switchstar'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountDocumentsRouteImport } from './routes/account.documents'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountServicesRouteImport } from './routes/account.services'
import { Route as AccountSupportRouteImport } from './routes/account.support'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminOrganisationsRouteImport } from './routes/admin.organisations'
import { Route as AdminPeopleRouteImport } from './routes/admin.people'
import { Route as DeveloperIndexRouteImport } from './routes/developer.index'
import { Route as DeveloperSitesRouteImport } from './routes/developer.sites'
import { Route as OperatorIndexRouteImport } from './routes/operator.index'
import { Route as OperatorRequestsRouteImport } from './routes/operator.requests'
import { Route as OperatorSitesRouteImport } from './routes/operator.sites'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffCustomersRouteImport } from './routes/staff.customers'
import { Route as StaffEnquiriesRouteImport } from './routes/staff.enquiries'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RetirementLivingRoute = RetirementLivingRouteImport.update({
  id: '/retirement-living',
  path: '/retirement-living',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SwitchstarRoute = SwitchstarRouteImport.update({
  id: '/switchstar',
  path: '/switchstar',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountDocumentsRoute = AccountDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountServicesRoute = AccountServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSupportRoute = AccountSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganisationsRoute = AdminOrganisationsRouteImport.update({
  id: '/organisations',
  path: '/organisations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPeopleRoute = AdminPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AdminRoute,
} as any)
const DeveloperIndexRoute = DeveloperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperSitesRoute = DeveloperSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => DeveloperRoute,
} as any)
const OperatorIndexRoute = OperatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorRequestsRoute = OperatorRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorSitesRoute = OperatorSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => OperatorRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCustomersRoute = StaffCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => StaffRoute,
} as any)
const StaffEnquiriesRoute = StaffEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => StaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/developer': typeof DeveloperRouteWithChildren
  '/operator': typeof OperatorRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/retirement-living': typeof RetirementLivingRoute
  '/staff': typeof StaffRouteWithChildren
  '/support': typeof SupportRoute
  '/switchstar': typeof SwitchstarRoute
  '/account/documents': typeof AccountDocumentsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/services': typeof AccountServicesRoute
  '/account/support': typeof AccountSupportRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/organisations': typeof AdminOrganisationsRoute
  '/admin/people': typeof AdminPeopleRoute
  '/developer/sites': typeof DeveloperSitesRoute
  '/operator/requests': typeof OperatorRequestsRoute
  '/operator/sites': typeof OperatorSitesRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/staff/customers': typeof StaffCustomersRoute
  '/staff/enquiries': typeof StaffEnquiriesRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/retirement-living': typeof RetirementLivingRoute
  '/support': typeof SupportRoute
  '/switchstar': typeof SwitchstarRoute
  '/account/documents': typeof AccountDocumentsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/services': typeof AccountServicesRoute
  '/account/support': typeof AccountSupportRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/organisations': typeof AdminOrganisationsRoute
  '/admin/people': typeof AdminPeopleRoute
  '/developer/sites': typeof DeveloperSitesRoute
  '/operator/requests': typeof OperatorRequestsRoute
  '/operator/sites': typeof OperatorSitesRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/staff/customers': typeof StaffCustomersRoute
  '/staff/enquiries': typeof StaffEnquiriesRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/developer': typeof DeveloperIndexRoute
  '/operator': typeof OperatorIndexRoute
  '/services': typeof ServicesIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/developer': typeof DeveloperRouteWithChildren
  '/operator': typeof OperatorRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/retirement-living': typeof RetirementLivingRoute
  '/staff': typeof StaffRouteWithChildren
  '/support': typeof SupportRoute
  '/switchstar': typeof SwitchstarRoute
  '/account/documents': typeof AccountDocumentsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/services': typeof AccountServicesRoute
  '/account/support': typeof AccountSupportRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/organisations': typeof AdminOrganisationsRoute
  '/admin/people': typeof AdminPeopleRoute
  '/developer/sites': typeof DeveloperSitesRoute
  '/operator/requests': typeof OperatorRequestsRoute
  '/operator/sites': typeof OperatorSitesRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/staff/customers': typeof StaffCustomersRoute
  '/staff/enquiries': typeof StaffEnquiriesRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/developer'
    | '/operator'
    | '/reset-password'
    | '/resources'
    | '/retirement-living'
    | '/staff'
    | '/support'
    | '/switchstar'
    | '/account/documents'
    | '/account/profile'
    | '/account/services'
    | '/account/support'
    | '/admin/content'
    | '/admin/organisations'
    | '/admin/people'
    | '/developer/sites'
    | '/operator/requests'
    | '/operator/sites'
    | '/services/$slug'
    | '/staff/customers'
    | '/staff/enquiries'
    | '/account/'
    | '/admin/'
    | '/developer/'
    | '/operator/'
    | '/services/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/reset-password'
    | '/resources'
    | '/retirement-living'
    | '/support'
    | '/switchstar'
    | '/account/documents'
    | '/account/profile'
    | '/account/services'
    | '/account/support'
    | '/admin/content'
    | '/admin/organisations'
    | '/admin/people'
    | '/developer/sites'
    | '/operator/requests'
    | '/operator/sites'
    | '/services/$slug'
    | '/staff/customers'
    | '/staff/enquiries'
    | '/account'
    | '/admin'
    | '/developer'
    | '/operator'
    | '/services'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/developer'
    | '/operator'
    | '/reset-password'
    | '/resources'
    | '/retirement-living'
    | '/staff'
    | '/support'
    | '/switchstar'
    | '/account/documents'
    | '/account/profile'
    | '/account/services'
    | '/account/support'
    | '/admin/content'
    | '/admin/organisations'
    | '/admin/people'
    | '/developer/sites'
    | '/operator/requests'
    | '/operator/sites'
    | '/services/$slug'
    | '/staff/customers'
    | '/staff/enquiries'
    | '/account/'
    | '/admin/'
    | '/developer/'
    | '/operator/'
    | '/services/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DeveloperRoute: typeof DeveloperRouteWithChildren
  OperatorRoute: typeof OperatorRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  RetirementLivingRoute: typeof RetirementLivingRoute
  StaffRoute: typeof StaffRouteWithChildren
  SupportRoute: typeof SupportRoute
  SwitchstarRoute: typeof SwitchstarRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retirement-living': {
      id: '/retirement-living'
      path: '/retirement-living'
      fullPath: '/retirement-living'
      preLoaderRoute: typeof RetirementLivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/switchstar': {
      id: '/switchstar'
      path: '/switchstar'
      fullPath: '/switchstar'
      preLoaderRoute: typeof SwitchstarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/documents': {
      id: '/account/documents'
      path: '/documents'
      fullPath: '/account/documents'
      preLoaderRoute: typeof AccountDocumentsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/services': {
      id: '/account/services'
      path: '/services'
      fullPath: '/account/services'
      preLoaderRoute: typeof AccountServicesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/support': {
      id: '/account/support'
      path: '/support'
      fullPath: '/account/support'
      preLoaderRoute: typeof AccountSupportRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organisations': {
      id: '/admin/organisations'
      path: '/organisations'
      fullPath: '/admin/organisations'
      preLoaderRoute: typeof AdminOrganisationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/people': {
      id: '/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AdminPeopleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/developer/': {
      id: '/developer/'
      path: '/'
      fullPath: '/developer/'
      preLoaderRoute: typeof DeveloperIndexRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/sites': {
      id: '/developer/sites'
      path: '/sites'
      fullPath: '/developer/sites'
      preLoaderRoute: typeof DeveloperSitesRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/operator/': {
      id: '/operator/'
      path: '/'
      fullPath: '/operator/'
      preLoaderRoute: typeof OperatorIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/requests': {
      id: '/operator/requests'
      path: '/requests'
      fullPath: '/operator/requests'
      preLoaderRoute: typeof OperatorRequestsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/sites': {
      id: '/operator/sites'
      path: '/sites'
      fullPath: '/operator/sites'
      preLoaderRoute: typeof OperatorSitesRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/customers': {
      id: '/staff/customers'
      path: '/customers'
      fullPath: '/staff/customers'
      preLoaderRoute: typeof StaffCustomersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/enquiries': {
      id: '/staff/enquiries'
      path: '/enquiries'
      fullPath: '/staff/enquiries'
      preLoaderRoute: typeof StaffEnquiriesRouteImport
      parentRoute: typeof StaffRoute
    }
  }
}

interface AccountRouteChildren {
  AccountDocumentsRoute: typeof AccountDocumentsRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountServicesRoute: typeof AccountServicesRoute
  AccountSupportRoute: typeof AccountSupportRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountDocumentsRoute: AccountDocumentsRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountServicesRoute: AccountServicesRoute,
  AccountSupportRoute: AccountSupportRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminOrganisationsRoute: typeof AdminOrganisationsRoute
  AdminPeopleRoute: typeof AdminPeopleRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminOrganisationsRoute: AdminOrganisationsRoute,
  AdminPeopleRoute: AdminPeopleRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DeveloperRouteChildren {
  DeveloperSitesRoute: typeof DeveloperSitesRoute
  DeveloperIndexRoute: typeof DeveloperIndexRoute
}

const DeveloperRouteChildren: DeveloperRouteChildren = {
  DeveloperSitesRoute: DeveloperSitesRoute,
  DeveloperIndexRoute: DeveloperIndexRoute,
}

const DeveloperRouteWithChildren = DeveloperRoute._addFileChildren(
  DeveloperRouteChildren,
)

interface OperatorRouteChildren {
  OperatorRequestsRoute: typeof OperatorRequestsRoute
  OperatorSitesRoute: typeof OperatorSitesRoute
  OperatorIndexRoute: typeof OperatorIndexRoute
}

const OperatorRouteChildren: OperatorRouteChildren = {
  OperatorRequestsRoute: OperatorRequestsRoute,
  OperatorSitesRoute: OperatorSitesRoute,
  OperatorIndexRoute: OperatorIndexRoute,
}

const OperatorRouteWithChildren = OperatorRoute._addFileChildren(
  OperatorRouteChildren,
)

interface StaffRouteChildren {
  StaffCustomersRoute: typeof StaffCustomersRoute
  StaffEnquiriesRoute: typeof StaffEnquiriesRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffCustomersRoute: StaffCustomersRoute,
  StaffEnquiriesRoute: StaffEnquiriesRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DeveloperRoute: DeveloperRouteWithChildren,
  OperatorRoute: OperatorRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  RetirementLivingRoute: RetirementLivingRoute,
  StaffRoute: StaffRouteWithChildren,
  SupportRoute: SupportRoute,
  SwitchstarRoute: SwitchstarRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
